<a href="https://colab.research.google.com/github/AliMdRamjan/Library/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version", tf.    __version__)
import keras as keras
print(keras.__version__, tf.__version__)

TensorFlow version 2.6.0
2.6.0 2.6.0


In [ ]:
#Load and prepare the MNIST dataset. Convert the samples from integers to floating-point numbers:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
#Build the tf.keras.Sequential model by stacking layers. Choose an optimizer and loss function for training:
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10)
])
#For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.54723966,  0.27362284,  0.90128607, -0.5281349 , -0.44909555,
         0.2895608 ,  0.02160904,  0.56466323,  0.18021215,  0.00820382]],
      dtype=float32)

In [ ]:
# Logitis a function that is used to maps probabilitie
#The tf.nn.softmax function converts these logits to "probabilities" for each class:
tf.nn.softmax(predictions).numpy # tf.nn.softmax _-function

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.04859192, 0.11042313, 0.20684773, 0.04952918, 0.0536028 ,
        0.11219715, 0.08582461, 0.14772613, 0.10057553, 0.08468179]],
      dtype=float32)>>

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.1874976

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=2) #eposchs?

Epoch 1/2
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0280 - accuracy: 0.9906
Epoch 2/2
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0292 - accuracy: 0.9900


In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0268 - accuracy: 0.9909
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0272 - accuracy: 0.9905
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0247 - accuracy: 0.9912
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0252 - accuracy: 0.9916
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0241 - accuracy: 0.9916
